[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Haron-Prime/Antares'

[[plugins]]
repo = 'AlessandroYorba/Alduin'

[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'othree/yajs'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'thinca/vim-template'
hook_add = '''
let g:template_basedir = '~/.config/nvim'
let g:template_free_pattern = 'template'
'''

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'mhartington/nvim-typescript'

[[plugins]]
repo = 'ianks/vim-tsx'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'rhysd/vim-clang-format'

[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'sophacles/vim-processing'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'pdurbin/vim-tsv'

[[plugins]]
repo = 'heavenshell/vim-pydocstring'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'dzeban/vim-log-syntax'

[[plugins]]
repo = 'isRuslan/vim-es6'
