version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: apt update
          command: apt update
      - run:
          name: minimum depends
          command: apt install -y build-essential git
      - run:
          name: make test
          command: make
