[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'scrooloose/nerdtree'

# js
[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
