[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Haron-Prime/Antares'

[[plugins]]
repo = 'AlessandroYorba/Alduin'

[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'thinca/vim-template'
hook_add = '''
let g:template_basedir = '~/.config/nvim'
let g:template_free_pattern = 'template'
'''

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'mhartington/nvim-typescript'

[[plugins]]
repo = 'ianks/vim-tsx'

[[plugins]]
repo = 'baabelfish/nvim-nim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'rhysd/vim-clang-format'

[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'honeytrap15/nvim-nimble'
